language: java

cache:
  directories:
    - $HOME/.m2

sudo: false

services:
  - docker

install: true

script:
  - "echo 'microsoft/mssql-server-linux:2017-CU6' > spring-data-jdbc/src/test/resources/container-license-acceptance.txt"
  - "./mvnw -version"
  - "./mvnw -Pjava11 clean dependency:list test -Pall-dbs${NO_JACOCO:+',no-jacoco'} -Dsort -U"
